- name: Configure chassis OVN remote
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - set
      - open
      - "."
      - "external-ids:ovn-remote={{ ovn_chassis_remote }}"
  changed_when: true

- name: Configure chassis encapsulation type
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - set
      - open
      - "."
      - "external-ids:ovn-encap-type={{ ovn_chassis_encap_type }}"
  changed_when: true

- name: Configure chassis encapsulation address
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - set
      - open
      - "."
      - "external-ids:ovn-encap-ip={{ ovn_chassis_effective_encap_ip }}"
  changed_when: true

- name: Configure chassis system ID
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - set
      - open
      - "."
      - "external-ids:system-id={{ ovn_chassis_name }}"
  changed_when: true

- name: Configure chassis integration bridge
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - set
      - open
      - "."
      - "external-ids:ovn-bridge={{ ovn_chassis_integration_bridge }}"
  changed_when: true

- name: Configure chassis CMS options
  when: ovn_chassis_cms_options | length > 0
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - set
      - open
      - "."
      - "external-ids:ovn-cms-options={{ ovn_chassis_cms_options | join(',') }}"
  changed_when: true

- name: Clear chassis CMS options
  when: ovn_chassis_cms_options | length == 0
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - remove
      - open
      - "."
      - external_ids
      - ovn-cms-options
  changed_when: true

- name: Configure chassis monitor-all
  when: ovn_chassis_monitor_all | bool
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - set
      - open
      - "."
      - external-ids:ovn-monitor-all=true
  changed_when: true

- name: Clear chassis monitor-all
  when: not (ovn_chassis_monitor_all | bool)
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - remove
      - open
      - "."
      - external_ids
      - ovn-monitor-all
  changed_when: true

- name: Create chassis bridges
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - --may-exist
      - add-br
      - "{{ item }}"
  loop: >-
    {{ ([ovn_chassis_integration_bridge] + ovn_chassis_bridges) | unique }}
  changed_when: true

- name: Configure chassis bridge mappings
  when: ovn_chassis_bridge_mappings | length > 0
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - set
      - open
      - "."
      - "external-ids:ovn-bridge-mappings={{ ovn_chassis_bridge_mappings }}"
  changed_when: true

- name: Clear chassis bridge mappings
  when: ovn_chassis_bridge_mappings | length == 0
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - remove
      - open
      - "."
      - external_ids
      - ovn-bridge-mappings
  changed_when: true
