- name: Validate OVN artifact
  ansible.builtin.include_role:
    name: ovn_artifact
    public: true
  vars:
    ovn_artifact_action: validate

- name: Install DPDK runtime dependencies
  when: ovn_install_dpdk_enabled | bool
  ansible.builtin.include_role:
    name: distro_packages
  vars:
    distro_packages_names: "{{ ovn_install_dpdk_runtime_package_names }}"

- name: Install OVN artifact
  ansible.builtin.unarchive:
    src: "{{ ovn_artifact_local_path }}"
    dest: /

- name: Refresh shared library cache
  ansible.builtin.command:
    cmd: ldconfig
  changed_when: true

- name: Mark OVS as installed from OVN artifact
  ansible.builtin.set_fact:
    ovs_installed: true
