- name: Install OVS and OVN from distro repos
  ansible.builtin.include_role:
    name: distro_packages
  vars:
    distro_packages_names: "{{ ovn_install_distro_package_names }}"
    distro_packages_repository_names: "{{ ovn_install_distro_repository_package_names }}"
    distro_packages_state: "{{ 'latest' if ovn_install_distro_version == 'latest' else 'present' }}"

- name: Mark OVS as installed (included in OVN distro packages)
  ansible.builtin.set_fact:
    ovs_installed: true
