- name: Install OVN from source
  when: ovn_install_method == "source"
  ansible.builtin.include_tasks: source.yml

- name: Install OVN from git
  when: ovn_install_method == "git"
  ansible.builtin.include_tasks: git.yml

- name: Install OVN from distro repos
  when: ovn_install_method == "distro"
  ansible.builtin.include_tasks: distro.yml

- name: Install OVN from package files
  when: ovn_install_method == "package"
  ansible.builtin.include_tasks: package.yml
