- name: Verify OVS external IDs
  ansible.builtin.assert:
    that:
      - ovs_external_ids is mapping
      - ovs_external_ids.keys() | reject('equalto', '') | length == ovs_external_ids | length
    fail_msg: "OVS external IDs must be a mapping with nonempty keys."

- name: Set OVS external IDs
  when: ovs_external_id.value is not none
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - set
      - Open_vSwitch
      - .
      - "external_ids:{{ ovs_external_id.key }}={{ ovs_external_id.value }}"
  loop: "{{ ovs_external_ids | dict2items }}"
  loop_control:
    loop_var: ovs_external_id
    label: "{{ ovs_external_id.key }}"
  changed_when: true

- name: Remove OVS external IDs
  when: ovs_external_id.value is none
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - remove
      - Open_vSwitch
      - .
      - external_ids
      - "{{ ovs_external_id.key }}"
  loop: "{{ ovs_external_ids | dict2items }}"
  loop_control:
    loop_var: ovs_external_id
    label: "{{ ovs_external_id.key }}"
  changed_when: true
