- name: Clean managed DHCP state for {{ ovn_endpoint.name }}
  ansible.builtin.include_tasks: dhcp_cleanup.yml

- name: Clean OVS namespace for {{ ovn_endpoint.name }}
  ansible.builtin.include_role:
    name: ovs_endpoints
    tasks_from: cleanup.yml
  vars:
    ovs_endpoint: "{{ ovn_endpoint }}"
