- name: Create network namespace for {{ ovn_endpoint.name }}
  ansible.builtin.command:
    cmd: "ip netns add {{ ovn_endpoint.name }}"
    creates: "/var/run/netns/{{ ovn_endpoint.name }}"

- name: Create veth pair for {{ ovn_endpoint.name }}
  ansible.builtin.command:
    cmd: >-
      ip link add {{ ovn_endpoint.name }}-p type veth
      peer name {{ ovn_endpoint.name }}
    creates: "/sys/class/net/{{ ovn_endpoint.name }}-p"

- name: Move interface into namespace for {{ ovn_endpoint.name }}
  ansible.builtin.command:
    cmd: >-
      ip link set {{ ovn_endpoint.name }} netns {{ ovn_endpoint.name }}
    removes: "/sys/class/net/{{ ovn_endpoint.name }}"

- name: Find current OVS bridge for {{ ovn_endpoint.name }}
  ansible.builtin.command:
    cmd: "ovs-vsctl port-to-br {{ ovn_endpoint.name }}-p"
  register: ovn_endpoint_current_bridge
  failed_when: false
  changed_when: false

- name: Detach from old OVS bridge for {{ ovn_endpoint.name }}
  when:
    - ovn_endpoint_current_bridge.rc == 0
    - ovn_endpoint_current_bridge.stdout != ovn_endpoint_bridge
  ansible.builtin.command:
    cmd: >-
      ovs-vsctl del-port {{ ovn_endpoint_current_bridge.stdout }}
      {{ ovn_endpoint.name }}-p
  changed_when: true

- name: Attach to the integration bridge for {{ ovn_endpoint.name }}
  ansible.builtin.command:
    cmd: >-
      ovs-vsctl --may-exist add-port {{ ovn_endpoint_bridge }}
      {{ ovn_endpoint.name }}-p
      -- set Interface {{ ovn_endpoint.name }}-p
      external_ids:iface-id={{ ovn_endpoint.iface_id }}
  changed_when: true

- name: Bring up host interface for {{ ovn_endpoint.name }}
  ansible.builtin.command:
    cmd: "ip link set {{ ovn_endpoint.name }}-p up"
  changed_when: true

- name: Configure interface for {{ ovn_endpoint.name }}
  ansible.builtin.command:
    cmd: "ip netns exec {{ ovn_endpoint.name }} {{ item }}"
  loop:
    - ip link set lo up
    - "ip link set {{ ovn_endpoint.name }} address {{ ovn_endpoint.mac }}"
    - "ip link set {{ ovn_endpoint.name }} up"
    - "ip -4 route flush table all dev {{ ovn_endpoint.name }} proto boot"
    - "ip -6 route flush table all dev {{ ovn_endpoint.name }} proto boot"
    - "ip address flush dev {{ ovn_endpoint.name }} scope global"
  changed_when: true

- name: Configure addresses for {{ ovn_endpoint.name }}
  ansible.builtin.command:
    cmd: >-
      ip netns exec {{ ovn_endpoint.name }} ip address replace
      {{ item }} dev {{ ovn_endpoint.name }}
  loop: "{{ ovn_endpoint.addresses | default([]) }}"
  changed_when: true

- name: Configure routes for {{ ovn_endpoint.name }}
  ansible.builtin.command:
    cmd: >-
      ip netns exec {{ ovn_endpoint.name }}
      ip -{{ ovn_route.family
              | default(6 if ':' in
                ((ovn_route.to | string)
                 ~ (ovn_route.via | default('') | string))
                else 4) }}
      route replace {{ ovn_route.to }}
      {% if ovn_route.via is defined %}via {{ ovn_route.via }}{% endif %}
      dev {{ ovn_endpoint.name }}
      {% if ovn_route.metric is defined %}metric {{ ovn_route.metric }}{% endif %}
      {% if ovn_route.table is defined %}table {{ ovn_route.table }}{% endif %}
  loop: "{{ ovn_endpoint.routes | default([]) }}"
  loop_control:
    loop_var: ovn_route
    label: "{{ ovn_route.to }}"
  changed_when: true
