- name: Read clustered OVN database remotes
  ansible.builtin.command:
    argv:
      - ovn-appctl
      - -t
      - "{{ item.socket }}"
      - ovsdb-server/list-remotes
  loop: "{{ ovn_central_databases }}"
  loop_control:
    label: "{{ item.name }}"
  register: ovn_central_database_remotes
  changed_when: false

- name: Remove obsolete clustered OVN database remotes
  when:
    - item.1 is not match('^punix:')
    - item.1 != item.0.item.listener
  ansible.builtin.command:
    argv:
      - ovn-appctl
      - -t
      - "{{ item.0.item.socket }}"
      - ovsdb-server/remove-remote
      - "{{ item.1 }}"
  loop: >-
    {{ ovn_central_database_remotes.results
       | subelements('stdout_lines', skip_missing=true) }}
  loop_control:
    label: "{{ item.1 }}"
  changed_when: true

- name: Add clustered OVN database listeners
  when: item.listener not in ovn_central_existing_remotes.stdout_lines
  ansible.builtin.command:
    argv:
      - ovn-appctl
      - -t
      - "{{ item.socket }}"
      - ovsdb-server/add-remote
      - "{{ item.listener }}"
  loop: "{{ ovn_central_databases }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    ovn_central_existing_remotes: >-
      {{ ovn_central_database_remotes.results
         | selectattr('item.id', 'equalto', item.id) | first }}
  changed_when: true
