- name: Reconcile OVN clustered databases
  ansible.builtin.include_tasks: reconcile-database.yml
  loop: "{{ ovn_central_databases }}"
  loop_control:
    loop_var: ovn_central_database
    label: "{{ ovn_central_database.name }}"
