ovn_central_install_packages: true
ovn_central_package_names:
  dnf:
    - ovn-central
  apt:
    - ovn-central
ovn_central_repository_package_names:
  dnf: []
  apt: []

ovn_nb_port: 6641
ovn_sb_port: 6642
ovn_cluster_members: []
ovn_ssl_enabled: false
ovn_log_level: info
ovn_db_dir: /var/lib/openvswitch

ovn_ssl_private_key: /etc/openvswitch/ovn-privkey.pem
ovn_ssl_certificate: /etc/openvswitch/ovn-cert.pem
ovn_ssl_ca_cert: /etc/openvswitch/cacert.pem
