- name: Find OVS bridge for {{ ovs_endpoint.name }}
  ansible.builtin.command:
    cmd: "ovs-vsctl port-to-br {{ ovs_endpoint_host_interface }}"
  register: ovs_endpoint_cleanup_bridge
  failed_when: false
  changed_when: false

- name: Detach OVS endpoint {{ ovs_endpoint.name }}
  when: ovs_endpoint_cleanup_bridge.rc == 0
  ansible.builtin.command:
    cmd: >-
      ovs-vsctl del-port {{ ovs_endpoint_cleanup_bridge.stdout }}
      {{ ovs_endpoint_host_interface }}
  changed_when: true

- name: Delete host interface for {{ ovs_endpoint.name }}
  ansible.builtin.command:
    cmd: "ip link delete {{ ovs_endpoint_host_interface }}"
    removes: "/sys/class/net/{{ ovs_endpoint_host_interface }}"

- name: Delete network namespace for {{ ovs_endpoint.name }}
  ansible.builtin.command:
    cmd: "ip netns delete {{ ovs_endpoint.name }}"
    removes: "/var/run/netns/{{ ovs_endpoint.name }}"
