- name: Create network namespace for {{ ovs_endpoint.name }}
  ansible.builtin.command:
    cmd: "ip netns add {{ ovs_endpoint.name }}"
    creates: "/var/run/netns/{{ ovs_endpoint.name }}"

- name: Create veth pair for {{ ovs_endpoint.name }}
  ansible.builtin.command:
    cmd: >-
      ip link add {{ ovs_endpoint.name }}-p type veth
      peer name {{ ovs_endpoint.name }}
    creates: "/sys/class/net/{{ ovs_endpoint.name }}-p"

- name: Move interface into namespace for {{ ovs_endpoint.name }}
  ansible.builtin.command:
    cmd: >-
      ip link set {{ ovs_endpoint.name }} netns {{ ovs_endpoint.name }}
    removes: "/sys/class/net/{{ ovs_endpoint.name }}"

- name: Find current OVS bridge for {{ ovs_endpoint.name }}
  ansible.builtin.command:
    cmd: "ovs-vsctl port-to-br {{ ovs_endpoint.name }}-p"
  register: ovs_endpoint_current_bridge
  failed_when: false
  changed_when: false

- name: Detach from old OVS bridge for {{ ovs_endpoint.name }}
  when:
    - ovs_endpoint_current_bridge.rc == 0
    - ovs_endpoint_current_bridge.stdout != ovs_endpoint.bridge
  ansible.builtin.command:
    cmd: >-
      ovs-vsctl del-port {{ ovs_endpoint_current_bridge.stdout }}
      {{ ovs_endpoint.name }}-p
  changed_when: true

- name: Attach endpoint to {{ ovs_endpoint.bridge }}
  ansible.builtin.command:
    cmd: >-
      ovs-vsctl --may-exist add-port {{ ovs_endpoint.bridge }}
      {{ ovs_endpoint.name }}-p
      {% if ovs_endpoint.iface_id is defined %}
      -- set Interface {{ ovs_endpoint.name }}-p
      external_ids:iface-id={{ ovs_endpoint.iface_id }}
      {% endif %}
  changed_when: true

- name: Configure host interface for {{ ovs_endpoint.name }}
  ansible.builtin.command:
    cmd: "ip link set {{ ovs_endpoint.name }}-p {{ item }}"
  loop:
    - >-
      mtu {{ ovs_endpoint.mtu | default(ovs_endpoint_mtu) }}
    - up
  changed_when: true

- name: Configure interface for {{ ovs_endpoint.name }}
  ansible.builtin.command:
    cmd: "ip netns exec {{ ovs_endpoint.name }} {{ item }}"
  loop:
    - ip link set lo up
    - "ip link set {{ ovs_endpoint.name }} address {{ ovs_endpoint.mac }}"
    - >-
      ip link set {{ ovs_endpoint.name }}
      mtu {{ ovs_endpoint.mtu | default(ovs_endpoint_mtu) }}
    - "ip link set {{ ovs_endpoint.name }} up"
    - "ip -4 route flush table all dev {{ ovs_endpoint.name }} proto boot"
    - "ip -6 route flush table all dev {{ ovs_endpoint.name }} proto boot"
    - "ip address flush dev {{ ovs_endpoint.name }} scope global"
  changed_when: true

- name: Configure addresses for {{ ovs_endpoint.name }}
  ansible.builtin.command:
    cmd: >-
      ip netns exec {{ ovs_endpoint.name }} ip address replace
      {{ item }} dev {{ ovs_endpoint.name }}
  loop: "{{ ovs_endpoint.addresses | default([]) }}"
  changed_when: true
