- name: Configure routes for {{ ovs_endpoint.name }}
  ansible.builtin.command:
    cmd: >-
      ip netns exec {{ ovs_endpoint.name }}
      ip -{{ ovs_route.family
              | default(6 if ':' in
                ((ovs_route.to | string)
                 ~ (ovs_route.via | default('') | string))
                else 4) }}
      route replace {{ ovs_route.to }}
      {% if ovs_route.via is defined %}via {{ ovs_route.via }}{% endif %}
      dev {{ ovs_endpoint.name }}
      {% if ovs_route.metric is defined %}metric {{ ovs_route.metric }}{% endif %}
      {% if ovs_route.table is defined %}table {{ ovs_route.table }}{% endif %}
  loop: "{{ ovs_endpoint.routes | default([]) }}"
  loop_control:
    loop_var: ovs_route
    label: "{{ ovs_route.to }}"
  changed_when: true
