- name: Check OVS bridge {{ ovs_bridge_name }}
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - br-exists
      - "{{ ovs_bridge_name }}"
  register: ovs_bridge_exists
  failed_when: ovs_bridge_exists.rc not in [0, 2]
  changed_when: false

- name: Create OVS bridge {{ ovs_bridge_name }}
  when:
    - ovs_bridge_state == 'present'
    - ovs_bridge_exists.rc == 2
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - --may-exist
      - add-br
      - "{{ ovs_bridge_name }}"
  changed_when: true

- name: Delete OVS bridge {{ ovs_bridge_name }}
  when:
    - ovs_bridge_state == 'absent'
    - ovs_bridge_exists.rc == 0
  ansible.builtin.command:
    argv:
      - ovs-vsctl
      - --if-exists
      - del-br
      - "{{ ovs_bridge_name }}"
  changed_when: true

- name: Record OVS bridge update {{ ovs_bridge_name }}
  when: >-
    (ovs_bridge_state == 'present' and ovs_bridge_exists.rc == 2)
    or (ovs_bridge_state == 'absent' and ovs_bridge_exists.rc == 0)
  ansible.builtin.set_fact:
    ovs_bridges_updated: true
  changed_when: false
