- name: Run make check
  community.general.make:
    chdir: "{{ make_check_source_dir }}"
    target: "{{ make_check_target }}"
    jobs: "{{ make_check_jobs }}"
    params: "{{ make_check_params }}"
