- name: Configure load balancer groups
  ansible.builtin.script:
    cmd: apply.py
    executable: python3
  environment:
    OVN_LOAD_BALANCER_GROUPS: >-
      {{ ovn_load_balancer_groups | to_json | b64encode
         if ovn_load_balancer_groups_path | length == 0
         else '' }}
    OVN_LOAD_BALANCER_GROUPS_PATH: "{{ ovn_load_balancer_groups_path }}"
  register: ovn_load_balancer_groups_result
  changed_when: >-
    ovn_load_balancer_groups_result.stdout == 'changed'
