- name: Verify logical static route states
  ansible.builtin.assert:
    that:
      - >-
        ovn_static_routes
        | map(attribute='state', default='present')
        | difference(['present', 'absent'])
        | length == 0
    fail_msg: "Logical static route states must be present or absent."

- name: Verify logical static route IDs are unique
  ansible.builtin.assert:
    that:
      - >-
        ovn_static_routes | map(attribute='id') | unique | length
        == ovn_static_routes | length
    fail_msg: "Logical static route IDs must be unique."

- name: Configure OVN logical static routes
  ansible.builtin.include_tasks: route.yml
  loop: "{{ ovn_static_routes }}"
  loop_control:
    loop_var: ovn_static_route
    label: "{{ ovn_static_route.id }}"
  vars:
    ovn_static_route_output_port: >-
      {{ ovn_static_route.output_port | default([]) | to_json }}
