- name: Allocate hugepages for DPDK
  hosts: all
  become: true
  tasks:
    - name: Reserve hugepages
      ansible.posix.sysctl:
        name: vm.nr_hugepages
        value: "{{ dpdk_hugepages_count | default(2048) }}"
        sysctl_set: true
