- name: Set up OVN central
  hosts: central
  become: true
  roles:
    - ovn_install
    - ovs_setup
    - ovn_central

- name: Set up OVN host on compute nodes
  hosts: compute
  become: true
  roles:
    - ovn_install
    - ovs_setup
    - ovn_host
  vars:
    ovn_remote: "tcp:{{ hostvars[groups['central'][0]]['ansible_host'] }}:6642"
