- name: Set up OVN central
  hosts: central
  become: true
  roles:
    - ovn-install
    - ovs-setup
    - ovn-central

- name: Set up OVN host on compute nodes
  hosts: compute
  become: true
  roles:
    - ovn-install
    - ovs-setup
    - ovn-host
  vars:
    ovn_remote: "tcp:{{ lookup('env', 'CENTRAL_HOSTNAME') }}:6642"
