- name: Configure OVN topology
  hosts: "{{ ovn_topology_central_hosts | default('central') }}"
  become: true
  roles:
    - ovn_switches
    - ovn_localnet_ports
    - ovn_routers
    - ovn_router_ports
    - ovn_static_routes
