- name: Install OVN test dependencies
  hosts: all
  become: true
  vars:
    ovn_test_package_names:
      dnf:
        - openssl
      apt:
        - openssl
  roles:
    - role: distro_packages
      vars:
        distro_package_names: "{{ ovn_test_package_names }}"
