- name: Configure OVS tunnel mesh
  hosts: "{{ ovs_tunnel_mesh_hosts | default('compute:gateway') }}"
  become: true
  roles:
    - role: ovs_tunnel_mesh
      ovs_tunnel_mesh_scope: >-
        {{ query(
             'inventory_hostnames',
             ovs_tunnel_mesh_hosts | default('compute:gateway')) }}
