ovs_setup_bridges: []
ovs_setup_service_name: auto
ovs_setup_service_enabled: true
ovs_setup_ovs_ctl_path: auto
ovs_setup_ssl_enabled: false
ovs_setup_ssl_private_key: /etc/openvswitch/ovs-privkey.pem
ovs_setup_ssl_certificate: /etc/openvswitch/ovs-cert.pem
ovs_setup_ssl_ca_cert: /etc/openvswitch/cacert.pem
