- name: Install OVS from distro packages
  when: ovs_install_method == "package"
  ansible.builtin.include_tasks: package.yml

- name: Install OVS from source
  when: ovs_install_method == "source"
  ansible.builtin.include_tasks: source.yml

- name: Install OVS from git
  when: ovs_install_method == "git"
  ansible.builtin.include_tasks: git.yml

- name: Configure OVS
  ansible.builtin.include_tasks: configure.yml
