ovn_sb_port: 6642
ovn_remote: "tcp:127.0.0.1:{{ ovn_sb_port }}"
ovn_encap_type: geneve
ovn_encap_ip: "{{ ansible_facts['default_ipv4']['address'] }}"
ovn_chassis_name: "{{ ansible_facts['hostname'] }}"
# These values are authoritative; empty values clear their OVS external IDs.
ovn_bridge_mappings: ""
ovn_cms_options: []
ovn_bridges:
  - br-int
