name: Self tests

on:
  workflow_call:
    inputs:
      plans:
        required: true
        type: string

permissions:
  contents: read

jobs:
  run:
    name: ${{ matrix.plan }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plan: ${{ fromJson(inputs.plans) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install self-test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible-core podman qemu-kvm libvirt-daemon-system libvirt-dev pkg-config genisoimage
          sudo pip install --break-system-packages --force-reinstall ansible-core
          pipx install 'tmt[provision-container,provision-virtual]'

      - name: Run tmt self-test plan
        run: >-
          sudo env PATH="$PATH"
          tmt run --all plan --name '/plans/self/${{ matrix.plan }}' provision --feeling-safe
